site_name: Knowledge Bank
docs_dir: bank
plugins:
  - mknotebooks
theme:
  name: material
markdown_extensions:
  - attr_list
  - codehilite
  - pymdownx.arithmatex
nav:
  - APIs:
    - GraphQL: APIs/graphql.md
    - API: APIs/api.md
    - REST: APIs/rest.md
  - Machine Learning:
    - Variational Autoencoder: machine-learning/vae/Variational Autoencoder.ipynb
  - Bayesian Statistics:
    - Bayesian Inference: bayesian-stats/Bayesian Inference.ipynb
  - Functional Programming:
    - Clojure:
      - Clojure for the Brave and True:
        - Intro: clojure/brave-and-true/intro.md
        - Control Flow: clojure/brave-and-true/control-flow.md
        - Data Structures: clojure/brave-and-true/data-structures.md
        - Functions: clojure/brave-and-true/functions.md
