site_name: Knowledge Bank
docs_dir: bank
plugins:
  - mknotebooks
theme:
  name: material
markdown_extensions:
  - attr_list
  - codehilite
  - pymdownx.arithmatex
nav:
  - APIs:
    - GraphQL: APIs/graphql.md
    - API: APIs/api.md
    - REST: APIs/rest.md
  - Networking:
    - Proxies: networking/proxy.md
  - Testing:
    - API Mock Testing: testing/api-mocking.md
  # - Machine Learning:
  #   - Variational Autoencoder: machine-learning/vae/Variational Autoencoder.ipynb
  - Functional Programming:
    - Core Tenets: functional-programming/func-programming.md
    - Clojure for the Brave and True:
      - Intro: clojure/brave-and-true/intro.md
      - Data Structures: clojure/brave-and-true/data-structures.md
      - Functions: clojure/brave-and-true/functions.md
  - Object-oriented Programming:
    - Core Tenets: oop/oop.md
